
# This file was *autogenerated* from the file grid.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_0p6 = RealNumber('0.6'); _sage_const_4 = Integer(4)
var("r,theta,phi");
def coordfunc(r,theta,phi,switch,shift=_sage_const_0 ):
    if switch=="yin":
        return (r*sin(theta)*cos(phi)+shift,r*sin(theta)*sin(phi),r*cos(theta))
    else:
        return (-r*sin(theta)*cos(phi)+shift,r*cos(theta),r*sin(theta)*sin(phi))
       
yin=(parametric_plot3d(coordfunc(_sage_const_1 ,theta,phi,"yin",_sage_const_1 ),(theta,pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ),(phi,-_sage_const_3 *pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ))+
  parametric_plot3d(coordfunc(_sage_const_0p6 ,theta,phi,"yin",_sage_const_1 ),(theta,pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ),(phi,-_sage_const_3 *pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ),color="yellow")+
   parametric_plot3d(coordfunc(r,theta,-_sage_const_3 *pi/_sage_const_4 ,"yin",_sage_const_1 ),(r,_sage_const_0p6 ,_sage_const_1 ),(theta,pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ))+
   parametric_plot3d(coordfunc(r,theta,_sage_const_3 *pi/_sage_const_4 ,"yin",_sage_const_1 ),(r,_sage_const_0p6 ,_sage_const_1 ),(theta,pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ))+
   parametric_plot3d(coordfunc(r,pi/_sage_const_4 ,phi,"yin",_sage_const_1 ),(r,_sage_const_0p6 ,_sage_const_1 ),(phi,-_sage_const_3 *pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ))+
   parametric_plot3d(coordfunc(r,_sage_const_3 *pi/_sage_const_4 ,phi,"yin",_sage_const_1 ),(r,_sage_const_0p6 ,_sage_const_1 ),(phi,-_sage_const_3 *pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ))
  )
yang=(parametric_plot3d(coordfunc(_sage_const_1 ,theta,phi,"yang",-_sage_const_1 ),(theta,pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ),(phi,-_sage_const_3 *pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ))+
  parametric_plot3d(coordfunc(_sage_const_0p6 ,theta,phi,"yang",-_sage_const_1 ),(theta,pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ),(phi,-_sage_const_3 *pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ),color="yellow")+
   parametric_plot3d(coordfunc(r,theta,-_sage_const_3 *pi/_sage_const_4 ,"yang",-_sage_const_1 ),(r,_sage_const_0p6 ,_sage_const_1 ),(theta,pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ))+
   parametric_plot3d(coordfunc(r,theta,_sage_const_3 *pi/_sage_const_4 ,"yang",-_sage_const_1 ),(r,_sage_const_0p6 ,_sage_const_1 ),(theta,pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ))+
   parametric_plot3d(coordfunc(r,pi/_sage_const_4 ,phi,"yang",-_sage_const_1 ),(r,_sage_const_0p6 ,_sage_const_1 ),(phi,-_sage_const_3 *pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ))+
   parametric_plot3d(coordfunc(r,_sage_const_3 *pi/_sage_const_4 ,phi,"yang",-_sage_const_1 ),(r,_sage_const_0p6 ,_sage_const_1 ),(phi,-_sage_const_3 *pi/_sage_const_4 ,_sage_const_3 *pi/_sage_const_4 ))
  )
show(yin+yang,aspect_ratio=_sage_const_1 )

