
# This file was *autogenerated* from the file quad.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_0p87 = RealNumber('0.87'); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_8p65 = RealNumber('8.65'); _sage_const_1p08 = RealNumber('1.08'); _sage_const_6 = Integer(6); _sage_const_1p9 = RealNumber('1.9'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_1p1 = RealNumber('1.1'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p0 = RealNumber('0.0'); _sage_const_0p2 = RealNumber('0.2'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_0p7 = RealNumber('0.7'); _sage_const_0p8 = RealNumber('0.8'); _sage_const_1p50 = RealNumber('1.50'); _sage_const_1p77 = RealNumber('1.77'); _sage_const_10 = Integer(10); _sage_const_0p57 = RealNumber('0.57'); _sage_const_14 = Integer(14); _sage_const_1p85 = RealNumber('1.85'); _sage_const_0p885 = RealNumber('0.885'); _sage_const_8p70 = RealNumber('8.70')
a1= arc((_sage_const_1 ,_sage_const_0 ), _sage_const_1 , angle=pi, sector=(-_sage_const_1 ,pi/_sage_const_3 ), color="blue",
        thickness=_sage_const_1 , zorder=_sage_const_5 )
f=(sqrt(_sage_const_1 -x**_sage_const_2 ) )
p=plot(f,-_sage_const_1 ,_sage_const_1 ,aspect_ratio=_sage_const_1 );p
q=plot(-f,-_sage_const_1 ,_sage_const_1 ,aspect_ratio=_sage_const_1 );q
l=line(((_sage_const_0p0 ,_sage_const_0 ),(_sage_const_0p57 ,_sage_const_1 )), color="red",thickness=_sage_const_1 )
l1=line(((_sage_const_0p57 ,_sage_const_0 ),(_sage_const_0p57 ,_sage_const_1 )), color="red",thickness=_sage_const_1 )
l2=line(((_sage_const_0p57 ,_sage_const_0 ),(_sage_const_0p57 ,-_sage_const_1 )), color="red",thickness=_sage_const_1 )
l3=line(((_sage_const_0 ,-_sage_const_1 ),(_sage_const_3 ,-_sage_const_1 )), color="blue",thickness=_sage_const_1 )
l4=line(((_sage_const_0p5 ,_sage_const_0 ),(_sage_const_0p5 ,_sage_const_0p87 )), color="blue",
        linestyle="dashed",thickness=_sage_const_1 )
l5=line(((_sage_const_0p5 ,_sage_const_0 ),(_sage_const_0p5 ,-_sage_const_0p87 )), color="blue",
        linestyle="dashed",thickness=_sage_const_1 )
l6=line(((_sage_const_0 ,_sage_const_1 ),(_sage_const_2 ,_sage_const_1 )), color="blue",thickness=_sage_const_1 )
l7=line(((_sage_const_0p57 ,_sage_const_1 ),(_sage_const_3 ,-_sage_const_1 )), color="red",thickness=_sage_const_1 )
A = text("A", (-_sage_const_0p1 ,_sage_const_1p1 ), color="black", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
B = text("H", (-_sage_const_0p1 ,-_sage_const_0p1 ), color="black", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
C = text("C", (-_sage_const_0p1 ,-_sage_const_1p1 ), color="black", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
D = text("D", (_sage_const_1 ,-_sage_const_1p1 ), color="black", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
F = text("F", (_sage_const_3 ,-_sage_const_1p1 ), color="black", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
E = text("E", (_sage_const_2 ,-_sage_const_1p1 ), color="black", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
H = text("H", (_sage_const_0p57 ,_sage_const_1p1 ), color="red", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
I = text("I", (_sage_const_0p5 ,-_sage_const_1p08 ), color="red", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
G = text("G", (_sage_const_0p57 ,_sage_const_0p7 ), color="blue", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
K = text("K", (_sage_const_0p57 ,-_sage_const_0p7 ), color="blue", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
Q= text("$30^o$", (_sage_const_0p2 ,_sage_const_0p8 ), color="red", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
O = text("O", (-_sage_const_1p1 ,-_sage_const_0p1 ), color="black", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
J = text("J", (_sage_const_1p1 ,-_sage_const_0p1 ), color="black", fontsize=_sage_const_10 ,rotation=_sage_const_0 )
show(p+q+l+l1+l2+l3+l4+l5+l6+l7+a1+A+B+C+D+E+F+G+H+I+K+Q+O+J,xmin=-_sage_const_1 ,
     xmax=_sage_const_3 ,ymax=_sage_const_2 ,ymin=-_sage_const_2 ,gridlines="minor",gridlinesstyle=dict(color="green",linestyle="-"),frame=True,figsize=_sage_const_6 ,fontsize=_sage_const_8 )
Tl= text("L",(_sage_const_0p0 ,_sage_const_1p9 ),fontsize=_sage_const_14 ,color="red")
Th= text("H",(_sage_const_0p0 ,-_sage_const_0p2 ),fontsize=_sage_const_14 ,color="red")
Tp= text("P",(-_sage_const_1p77 ,_sage_const_1p9 ),fontsize=_sage_const_14 ,color="red")
Tn= text("N",(-_sage_const_1p77 ,-_sage_const_0p2 ),fontsize=_sage_const_14 ,color="red")
Tm= text("M",(-_sage_const_1p1 ,_sage_const_0p1 ),fontsize=_sage_const_14 ,color="blue")
lf=line(((_sage_const_0 ,_sage_const_1p77 ),(_sage_const_3 ,_sage_const_0 )), color="red",thickness=_sage_const_1 /_sage_const_2 )
lh=line(((_sage_const_0p0 ,_sage_const_1p77 ),(_sage_const_0 ,_sage_const_0 )), color="red",thickness=_sage_const_1p50 )
lp=line(((-_sage_const_1p77 ,_sage_const_1p77 ),(_sage_const_0 ,_sage_const_1p77 )), color="red",thickness=_sage_const_1p50 )
ln=line(((-_sage_const_1p77 ,_sage_const_0 ),(_sage_const_0 ,_sage_const_0 )), color="red",thickness=_sage_const_1p50 )
pn=line(((-_sage_const_1p77 ,_sage_const_1p77 ),(-_sage_const_1p77 ,_sage_const_0 )), color="red",thickness=_sage_const_1p50 )
ph=line(((-_sage_const_1p77 ,_sage_const_1p77 ),(_sage_const_0 ,_sage_const_0 )), color="orange",linestyle="dashed",
        thickness=_sage_const_1p50 )
nl=line(((-_sage_const_1p77 ,_sage_const_0 ),(_sage_const_0p0 ,_sage_const_1p77 )), color="orange",linestyle="dashed",
        thickness=_sage_const_1p50 )
p = point((_sage_const_1p0 ,_sage_const_0 ), color="red",pointsize=_sage_const_10 , zorder=_sage_const_5 )
Q=line(((-_sage_const_1 ,_sage_const_0 ),(_sage_const_3 ,_sage_const_0 )), color="black",thickness=_sage_const_1 )
a = arc((_sage_const_1 ,_sage_const_0 ), _sage_const_2 , angle=pi/_sage_const_6 , sector=(-_sage_const_8p70 *pi/_sage_const_4 ,_sage_const_5 *pi/_sage_const_6 ),thickness=_sage_const_1 )
a1 = arc((_sage_const_0 ,_sage_const_0 ),_sage_const_1  , angle=pi/_sage_const_6 ,color="black", 
         sector=(-_sage_const_8p65 *pi/_sage_const_4 ,_sage_const_5 *pi/_sage_const_6 ),thickness=_sage_const_1 )
a2 = arc((_sage_const_0 ,_sage_const_0 ),_sage_const_1  , angle=pi/_sage_const_6 ,color="black", 
         sector=(-_sage_const_8p65 *pi/_sage_const_4 ,_sage_const_5 *pi/_sage_const_6 ),thickness=_sage_const_1 )
c = circle((-_sage_const_0p885 ,_sage_const_0p885 ),_sage_const_1 ,color="violet",zorder=-_sage_const_5 ,thickness=_sage_const_2 )
show(a+Q+p+Tl+a1+lf+lh+Th+Tp+lp+Tn+ln+pn+ph+nl+c+Tm+C+D+E+F, 
     xmin=-_sage_const_1p85 ,xmax=_sage_const_3 ,ymin=-_sage_const_2 ,ymax=_sage_const_2p5 ,
     gridlines="minor",gridlinesstyle=dict(color="green",
                         linestyle="-"),axes=False,frame=True)

