
# This file was *autogenerated* from the file y.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1p66 = RealNumber('1.66'); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_1p1 = RealNumber('1.1'); _sage_const_8 = Integer(8); _sage_const_0p99 = RealNumber('0.99'); _sage_const_0p66 = RealNumber('0.66'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p33 = RealNumber('0.33'); _sage_const_1p32 = RealNumber('1.32'); _sage_const_14 = Integer(14); _sage_const_4p8 = RealNumber('4.8'); _sage_const_6 = Integer(6)
var("y")
def f(x):
    if x<_sage_const_0 :
        return sqrt(-x**_sage_const_2 -_sage_const_2 *x)
    else:
        return -sqrt(-x**_sage_const_2 +_sage_const_2 *x)
a=plot(f,(x,-_sage_const_2 ,_sage_const_2 ),color='white',
       fill=sqrt(_sage_const_4 -x**_sage_const_2 ),fillcolor="black",alpha=_sage_const_0p1 )
b=plot(f,(x,-_sage_const_2 ,_sage_const_2 ),color='white',
       fill=-sqrt(_sage_const_4 -x**_sage_const_2 ),fillcolor="white",alpha=_sage_const_0p1 )
p = circle((_sage_const_0 ,_sage_const_0 ),_sage_const_2 ,color="red",zorder=-_sage_const_5 )
p4 = circle((_sage_const_0 ,_sage_const_0 ),_sage_const_2 ,color="red",zorder=-_sage_const_5 )
p5= circle((_sage_const_0 ,_sage_const_0 ),_sage_const_0p33 ,color="red",zorder=-_sage_const_5 )
p6= circle((_sage_const_0 ,_sage_const_0 ),_sage_const_0p66 ,color="red",zorder=-_sage_const_5 )
p7= circle((_sage_const_0 ,_sage_const_0 ),_sage_const_0p99 ,color="red",zorder=-_sage_const_5 )
p8= circle((_sage_const_0 ,_sage_const_0 ),_sage_const_1p32 ,color="red",zorder=-_sage_const_5 )
p9= circle((_sage_const_0 ,_sage_const_0 ),_sage_const_1p66 ,color="red",zorder=-_sage_const_5 )
d=plot(f,(x,-_sage_const_2 ,_sage_const_2 ),color='white',
       fill=sqrt(_sage_const_4 -x**_sage_const_2 ),fillcolor="lightgrey",alpha=_sage_const_0p1 );
p=plot(x,-_sage_const_2 ,_sage_const_2 ,color="white",
       fill=x,fillcolor="green");
#o=plot(-x,-2,2,color="white");
r=plot(-(x*_sage_const_1 /_sage_const_8 ),-_sage_const_2 ,_sage_const_2 ,color="yellow");
t=plot(x*_sage_const_1 /_sage_const_4 ,-_sage_const_2 ,_sage_const_2 ,color="green");
l=plot(x*_sage_const_1 /_sage_const_2 ,-_sage_const_2 ,_sage_const_2 ,color="red");
u=plot(x,-_sage_const_2 ,_sage_const_2 ,color="green");
v=plot(-x,-_sage_const_2 ,_sage_const_2 ,color="violet");
q=plot(f,(x,-_sage_const_2 ,_sage_const_2 ),color='white',
       fill=-sqrt(_sage_const_4 -x**_sage_const_2 ),fillcolor="red",alpha=_sage_const_0p1 )
# p3 = arrow((0,0),(2*cos(pi/6),2*sin(pi/6)),
       #    linestyle="dashed", color="red")
a2 = arrow((_sage_const_0 ,_sage_const_0 ), (_sage_const_2 *cos(pi/_sage_const_8 ),-sin(_sage_const_2 *pi/_sage_const_8 )), color="blue",
          linestyle="dashed",thickness=_sage_const_1 )
a3 = arrow((_sage_const_0 ,_sage_const_0 ), (_sage_const_3 *cos(pi/_sage_const_4p8 +pi/_sage_const_2 ),_sage_const_3 *sin(_sage_const_2 *pi/_sage_const_4p8 +pi/_sage_const_2 )),
          color="blue", linestyle="dashed",thickness=_sage_const_1 )
O = text("O", (-_sage_const_1p1 ,-_sage_const_0p1 ), color="black", fontsize=_sage_const_14 ,rotation=_sage_const_0 )
show(a+b+u+p4+a3+a2+p5+p6+p7+p8+p9,
     figsize=_sage_const_4 ,axes=True,aspect_ratio=_sage_const_1 ,
     gridlines="Minor",frame=True,fontsize=_sage_const_6 )

